name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a new feature! Your ideas help make Telegram Toolkit MCP better.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature
      placeholder: "What's the feature about?"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem does this feature solve?
      placeholder: |
        - What are you trying to do that you can't currently do?
        - Why is this important to you?
        - How does this fit into your workflow?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        - Describe the solution you'd like
        - Include mockups, API examples, or code snippets if helpful
        - Consider edge cases and error handling
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        - What other solutions have you considered?
        - Why is your proposed solution better?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical for my workflow
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small code changes)
        - Medium (moderate effort required)
        - Complex (significant effort required)
        - Very Complex (architectural changes needed)

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - label: New MCP tool
        - label: Enhanced existing tool
        - label: UI/UX improvement
        - label: Performance improvement
        - label: Security enhancement
        - label: Developer experience
        - label: Documentation
        - label: Other

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context or information
      placeholder: |
        - Related issues or discussions
        - Links to similar features in other tools
        - Any technical considerations

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with the project's goals
        - label: I understand that features are prioritized based on community interest
        - label: I understand that this is a volunteer-maintained project
